#!/bin/bash
#
# Title:      PSAutomate
# Based On:   PGBlitz (Reference Title File)
# Original Author(s):  Admin9705 - Deiteq
# PSAutomate Auther: fattylewis
# URL:        https://psautomate.io - http://github.psautomate.io
# GNU:        General Public License v3.0
################################################################################
---
- name: 'Deploying {{psarole}}'
  docker_container:
    name: '{{psarole}}'
    image: '{{imageselect.stdout}}'
    pull: yes
    published_ports:
      - '{{ext1}}:{{int1}}'
      - '{{serverports}}{{ext2}}:{{int2}}'
      - '{{serverports}}{{ext3}}:{{int3}}'
      - '{{serverports}}{{ext4}}:{{int4}}'
      - '{{serverports}}{{ext5}}:{{int5}}'
      - '{{serverports}}{{ext6}}:{{int6}}'
      - '{{serverports}}{{ext7}}:{{int7}}'
      - '{{serverports}}{{ext8}}:{{int8}}'
      - '{{serverports}}{{ext9}}:{{int9}}'

    volumes: '{{psa_volumes}}'
    devices: "{{ '/dev/dri:/dev/dri' if dev_dri.stat.exists == True | default(false) else omit }}"
    etc_hosts:
      { 'analytics.plex.tv': '127.0.0.1', 'metrics.plex.tv': '127.0.0.1' }
    env:
      PLEX_UID: '1000'
      PLEX_GID: '1000'
      ADVERTISE_IP: '{{customConnections}}'
    networks:
      - name: psautomate
        aliases:
          - '{{psarole}}'
    restart_policy: unless-stopped
    state: started
    labels: '{{psa_labels}}'
