#!/bin/bash
#
# Title:      PSAutomate
# Based On:   PGBlitz (Reference Title File)
# Original Author(s):  Admin9705 - Deiteq
# PSAutomate Auther: fattylewis
# URL:        https://psautomate.io - http://github.psautomate.io
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        int1: '8181'
        ext1: '8181'
        image: 'linuxserver/tautulli'

    # CORE (MANDATORY) ############################################################
    - name: 'Mandatory Core Role'
      include_tasks: '/psa/apps/_core.yml'

    - name: 'Including Plugins'
      include_tasks: '/psa/apps/_plugins.yml'

    - name: 'Checking for existing app data'
      stat:
        path: /psa/data/tautulli/config.ini
      register: confcheck

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        psa_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.port: '{{int1}}'
          traefik.frontend.rule: 'Host:{{psarole}}.{{domain}},{{tldset}}'

    - name: 'Setting PSA Volumes'
      set_fact:
        psa_volumes:
          - '/psa/data/{{psarole}}:/config'
          - '/psa/data/plex/database/Library/Application Support/Plex Media Server/Logs:/logs'
          - '/psa/data/{{psarole}}/scripts:/scripts'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PSA ENV'
      set_fact:
        psa_env:
          PUID: '1000'
          PGID: '1000'
          TZ: 'Europe/London'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{psarole}}'
      docker_container:
        name: '{{psarole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{serverports}}{{ext1}}:{{int1}}'
        volumes: '{{psa_volumes}}'
        env: '{{psa_env}}'
        restart_policy: unless-stopped
        networks:
          - name: psautomate
            aliases:
              - '{{psarole}}'
        state: started
        labels: '{{psa_labels}}'

    # AFTER ########################################################################
    - name: 'Configuring {{psarole}} for first time use'
      block:
        - name: 'Waiting for {{psarole}} to start'
          wait_for:
            path: '/psa/data/tautulli/config.ini'
            state: present

        - name: Stop Container
          docker_container:
            name: tautulli
            state: stopped

        - name: Restart {{psarole}}
          docker_container:
            name: '{{psarole}}'
            state: started

      when: not confcheck.stat.exists
